import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./component/header";
import { Footer } from "./component/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-6xl m-auto">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
