import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./component/header";
import { Footer } from "./component/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen flex justify-center">
          <div className="w-full max-w-6xl">
            <Header />
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
